name: Test Runner

on:
  push:
    branches: [ "master" ]

jobs:
  selenium-web-test:
    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v0.0.0
      with:
        chrome-options: '--headless'

    - name: Setup Gradlew
      run: chmod +x gradlew

    - name: Load Environment Variables
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env

    - name: Execute Test
      run: ./gradlew clean webTest

    - name: Archive test results
      uses: actions/upload-artifact@v4.3.0
      if: always() #always() # success() , failure(), canceled()
      with:
        name: cucumber reports
        path: target/index.html

  restAssured-API-test:
    needs: selenium-web-test
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradlew
        run: chmod +x gradlew

      - name: Load Environment Variables
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Execute Test
        run: ./gradlew clean apiTest